version: '3'

services:
  app:
    build: .
    entrypoint: entrypoint.sh
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
